# Generated by Django 2.2.4 on 2019-08-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0002_auto_20190829_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='title',
            field=models.CharField(default='Florence', max_length=2000),
            preserve_default=False,
        ),
    ]
