# Generated by Django 2.2.4 on 2019-11-06 08:41

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_auto_20190831_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='duration',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(datetime.timedelta(0))]),
        ),
    ]
